version: '3'

silent: true

tasks:
  default:
    - task: install

  install:
    - task: import
    # - . ./scripts/autohotkey.ps1
    # - Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
    # - . ./scripts/autohotkey.ps1
    - powershell ./scripts/autohotkey.ps1

  test:
    vars:
      SMILE: ":)"
      FROWN: "X("
      PWSH_PATH:
        # sh: if type pwsh > /dev/null 2>&1; then echo "True"; else echo "False"; fi
        sh: |
          if type "pwsh" > /dev/null 2>&1; then
          echo "pwsh"
          else
          echo "powershell"
          fi
    cmds:
      # - "{{if eq .PWSH_PATH 'True'}}{{.SMILE}}{{else}}{{.FROWN}}{{end}}"
      - echo "{{.PWSH_PATH}} ./scripts/autohotkey.ps1"
      - "{{.PWSH_PATH}} ./scripts/autohotkey.ps1"
      # - echo "{{.PWSH_PATH}}"

  update:
    - scoop update
    - scoop update *

  import:
    - scoop import Scoopfile.json
    - scoop uninstall vcredist2022

  export:
    - scoop export > Scoopfile.json
