version: '3'

silent: true

tasks:
  default:
    - task: install

  install:
    - task: import
    # - . ./scripts/autohotkey.ps1
    # - Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
    # - . ./scripts/autohotkey.ps1
    - powershell .\\scripts\\autohotkey.ps1

  update:
    - scoop update
    - scoop update *

  import:
    - scoop import Scoopfile.json
    - scoop uninstall vcredist2022

  export:
    - scoop export > Scoopfile.json
