version: '3'

silent: true

tasks:
  default:
    - task: install

  install:
    - task: import
    # - . ./scripts/autohotkey.ps1
    # - Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
    # - . ./scripts/autohotkey.ps1
    - powershell .\\scripts\\autohotkey.ps1

  test:
    vars:
      SMILE: ":)"
      FROWN: "X("
      PWSH_PATH:
        sh: $PSVersionTable.PSVersion.Major -ge 6
    cmds:
      # - echo {{if .PWSH_PATH}}{{.SMILE}}{{else}}{{.FROWN}}{{end}}
      # - echo {{.PWSH_PATH}}
      - echo {{.PWSH_PATH}}

  update:
    - scoop update
    - scoop update *

  import:
    - scoop import Scoopfile.json
    - scoop uninstall vcredist2022

  export:
    - scoop export > Scoopfile.json
